# Generated by Django 5.2 on 2025-07-30 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPCSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('penalty', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['section_number'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_description', models.TextField()),
                ('ollama_response', models.JSONField()),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analysis Histories',
                'ordering': ['-request_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_description', models.TextField(help_text='Description of the legal case')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_json', models.JSONField(help_text='Raw JSON response from Ollama model')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('primary_sections', models.ManyToManyField(related_name='primary_analyses', to='ipc_analysis.ipcsection')),
                ('legal_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='ipc_analysis.legalcase')),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
