# Generated by Django 4.2.7 on 2025-08-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('client', 'Client/Citizen'), ('lawyer', 'Lawyer/Legal Professional')], default='client', max_length=20),
        ),
    ]
