# Generated by Django 4.2.7 on 2025-08-05 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_analyses', models.PositiveIntegerField(default=0)),
                ('total_documents_processed', models.PositiveIntegerField(default=0)),
                ('total_cases_created', models.PositiveIntegerField(default=0)),
                ('total_lawyer_searches', models.PositiveIntegerField(default=0)),
                ('total_legal_research', models.PositiveIntegerField(default=0)),
                ('total_time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('total_files_uploaded', models.PositiveIntegerField(default=0)),
                ('total_file_size_mb', models.FloatField(default=0.0)),
                ('monthly_analyses', models.PositiveIntegerField(default=0)),
                ('monthly_documents', models.PositiveIntegerField(default=0)),
                ('monthly_cases', models.PositiveIntegerField(default=0)),
                ('current_month', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Analytics Data',
                'verbose_name_plural': 'User Analytics Data',
                'db_table': 'user_analytics_data',
            },
        ),
        migrations.CreateModel(
            name='UserActivityHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('document_analysis', 'Document Analysis'), ('case_analysis', 'Case Analysis'), ('ipc_analysis', 'IPC Section Analysis'), ('case_creation', 'Case Creation'), ('case_update', 'Case Update'), ('case_search', 'Case Search'), ('lawyer_search', 'Lawyer Search'), ('lawyer_contact', 'Lawyer Contact'), ('consultation_request', 'Consultation Request'), ('document_upload', 'Document Upload'), ('document_summarization', 'Document Summarization'), ('document_download', 'Document Download'), ('legal_case_study', 'Legal Case Study'), ('ipc_section_study', 'IPC Section Study'), ('legal_research', 'Legal Research'), ('login', 'User Login'), ('logout', 'User Logout'), ('profile_update', 'Profile Update'), ('dashboard_view', 'Dashboard View'), ('analytics_view', 'Analytics View'), ('report_generation', 'Report Generation')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='success', max_length=20)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('page_url', models.URLField(blank=True)),
                ('referrer_url', models.URLField(blank=True)),
                ('additional_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity History',
                'verbose_name_plural': 'User Activity Histories',
                'db_table': 'user_activity_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_activi_user_id_db2408_idx'), models.Index(fields=['activity_type', '-created_at'], name='user_activi_activit_9ca050_idx'), models.Index(fields=['status', '-created_at'], name='user_activi_status_5ee74a_idx')],
            },
        ),
    ]
