# Generated by Django 4.2.7 on 2025-08-06 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_useranalyticsdata_useractivityhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('user_type', models.CharField(choices=[('client', 'Client/Citizen'), ('lawyer', 'Lawyer/Legal Professional')], default='client', max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(blank=True, max_length=10)),
                ('bar_council_id', models.CharField(blank=True, max_length=50)),
                ('education', models.TextField(blank=True)),
                ('expertise', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('practice_areas', models.TextField(blank=True)),
                ('court_admissions', models.TextField(blank=True)),
                ('success_rate', models.IntegerField(blank=True, default=0)),
                ('total_cases', models.IntegerField(blank=True, default=0)),
                ('active_cases', models.IntegerField(blank=True, default=0)),
                ('rating', models.FloatField(blank=True, default=0.0)),
                ('reviews', models.IntegerField(blank=True, default=0)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('interests', models.TextField(blank=True)),
                ('preferred_languages', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
