version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ipc_justice_aid_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-ipc_justice_aid}
      POSTGRES_USER: ${DATABASE_USER:-ipc_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-ipc_password}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - ipc_justice_aid_network

  redis:
    image: redis:7-alpine
    container_name: ipc_justice_aid_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - ipc_justice_aid_network

  ollama:
    image: ollama/ollama:latest
    container_name: ipc_justice_aid_ollama
    restart: always
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
      - /home/anupam/.ollama:/host_ollama:ro
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - ipc_justice_aid_network

  web:
    build: .
    container_name: ipc_justice_aid_web
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
      - ollama
    environment:
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-ipc-justice-aid-secret-key}
      - DATABASE_NAME=${DATABASE_NAME:-ipc_justice_aid}
      - DATABASE_USER=${DATABASE_USER:-ipc_user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-ipc_password}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - OLLAMA_MODEL_NAME=${OLLAMA_MODEL_NAME:-Anupam/IPC-Helper:latest}
      - OLLAMA_TIMEOUT=${OLLAMA_TIMEOUT:-300}
      - OLLAMA_MAX_RETRIES=${OLLAMA_MAX_RETRIES:-2}
    env_file:
      - .env
    networks:
      - ipc_justice_aid_network

  celery_worker:
    build: .
    container_name: ipc_justice_aid_celery_worker
    restart: always
    command: celery -A ipc_justice_aid_backend worker --loglevel=info
    volumes:
      - .:/app
      - media_volume:/app/media
    depends_on:
      - db
      - redis
      - web
    environment:
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-ipc-justice-aid-secret-key}
      - DATABASE_NAME=${DATABASE_NAME:-ipc_justice_aid}
      - DATABASE_USER=${DATABASE_USER:-ipc_user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-ipc_password}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - OLLAMA_MODEL_NAME=${OLLAMA_MODEL_NAME:-Anupam/IPC-Helper:latest}
    env_file:
      - .env
    networks:
      - ipc_justice_aid_network

  celery_beat:
    build: .
    container_name: ipc_justice_aid_celery_beat
    restart: always
    command: celery -A ipc_justice_aid_backend beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web
    environment:
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-ipc-justice-aid-secret-key}
      - DATABASE_NAME=${DATABASE_NAME:-ipc_justice_aid}
      - DATABASE_USER=${DATABASE_USER:-ipc_user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-ipc_password}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    networks:
      - ipc_justice_aid_network

volumes:
  postgres_data:
  static_volume:
  media_volume:
  ollama_data:
  redis_data:

networks:
  ipc_justice_aid_network:
    driver: bridge
