version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ipc_justice_aid_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-ipc_justice_aid}
      POSTGRES_USER: ${DATABASE_USER:-ipc_user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-ipc_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - ipc_justice_aid_network

  web:
    build: .
    container_name: ipc_justice_aid_web
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
    environment:
      - DEBUG=${DEBUG:-True}
      - SECRET_KEY=${SECRET_KEY:-ipc-justice-aid-secret-key}
      - DATABASE_NAME=${DATABASE_NAME:-ipc_justice_aid}
      - DATABASE_USER=${DATABASE_USER:-ipc_user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-ipc_password}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - OLLAMA_MODEL_NAME=${OLLAMA_MODEL_NAME:-Anupam/IPC-Helper:latest}
    env_file:
      - .env
    networks:
      - ipc_justice_aid_network

  ollama:
    image: ollama/ollama:latest
    container_name: ipc_justice_aid_ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ipc_justice_aid_network
    # Uncomment the deploy section if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

volumes:
  postgres_data:
  static_volume:
  media_volume:
  ollama_data:

networks:
  ipc_justice_aid_network:
    driver: bridge
