[phases.setup]
nixPkgs = ["python39", "postgresql", "tesseract", "pkg-config", "libpng", "libjpeg", "freetype", "fontconfig"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn ipc_justice_aid_backend.wsgi:application --bind 0.0.0.0:$PORT"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
