web: gunicorn ipc_justice_aid_backend.wsgi:application --bind 0.0.0.0:$PORT
worker: celery -A ipc_justice_aid_backend worker --loglevel=info
beat: celery -A ipc_justice_aid_backend beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
